### ISSUE TITLE
Tweak tft_demo.toit configuration for ESP-WROVER-KIT V4.1

### ISSUE THREAD

**Issue by krzychb** [toitware/toit-color-tft#14]
The original tft_demo.toit example fails with the following exception:

```
EXCEPTION error.
  0: spi_device_               <sdk>/spi.toit:242:3
  1: Bus.device                <sdk>/spi.toit:95:10
  2: get_display               /Users/krzysztof/esp/toit/tft_demo/tft_demo.toit:49:17
  3: main                      /Users/krzysztof/esp/toit/tft_demo/tft_demo.toit:67:10
  4: __entry__.<lambda>        <sdk>/core/entry.toit:48:20
```

After discussion and kind help by Florian from Toit support, it turned out that SPI frequency for the pixel_display driver is set to high and the backlight pin state should be inverted.

A quick fix of both issues is possible by changing the following line:
https://github.com/toitware/toit-color-tft/blob/d590954f30b62fa9a28839762dff087a6d19df7c/examples/tft_demo.toit#L24

to:
```
WROVER_16_BIT_LANDSCAPE_SETTINGS          ::= [  26, 320, 240, 0,   0,   23, 19,   22, 21, 18,   null,     false, COLOR_TFT_16_BIT_MODE | COLOR_TFT_FLIP_XY ]
```
This update reduces the SPI frequency from 40 to [26.67 MHz](https://docs.espressif.com/projects/esp-idf/en/release-v4.3/esp32/api-reference/peripherals/spi_master.html#id12) and disables the operation of the backlight by the pixel_display driver. 
But we still need the backlight working. To enable the backlight outside the driver the following may be added in the `main`:

```
backlight_gpio := gpio.Pin 5 --output
backlight_gpio.set 0
```

**Comment by erikcorry** [comment]
I'm going to wait a little to land this.  The standard library is getting support for
inverted pins, and when that has been released, we can also release this
without breaking things for people on a current SDK.
